# Generated by Django 4.0.1 on 2022-01-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/user_defualt.png', upload_to='images'),
        ),
    ]
