# Generated by Django 4.0.1 on 2022-01-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user_defualt.png', upload_to='images'),
        ),
    ]
